GSW_8021X_EAPOL_RuleGet GSW_8021X_EAPOL_Rule_t 2 1
GSW_8021X_EAPOL_RuleSet GSW_8021X_EAPOL_Rule_t 0
GSW_8021X_PortCfgGet GSW_8021X_portCfg_t 2 0
GSW_8021X_PortCfgSet GSW_8021X_portCfg_t 0
GSW_MAC_TableClear 1
GSW_MAC_TableEntryAdd GSW_MAC_tableAdd_t 0
GSW_MAC_TableEntryQuery GSW_MAC_tableQuery_t 2 0 1
GSW_MAC_TableEntryRead GSW_MAC_tableRead_t 2 0
GSW_MAC_TableEntryRemove GSW_MAC_tableRemove_t 0
GSW_STP_BPDU_RuleGet GSW_STP_BPDU_Rule_t 3
GSW_STP_BPDU_RuleSet GSW_STP_BPDU_Rule_t 0
GSW_STP_PortCfgGet GSW_STP_portCfg_t 2 0
GSW_STP_PortCfgSet GSW_STP_portCfg_t 0
GSW_TrunkingCfgGet GSW_trunkingCfg_t 3
GSW_TrunkingCfgSet GSW_trunkingCfg_t 0
GSW_TrunkingPortCfgGet GSW_trunkingPortCfg_t 2 1
GSW_TrunkingPortCfgSet GSW_trunkingPortCfg_t 0
GSW_SVLAN_CfgGet GSW_SVLAN_cfg_t 3
GSW_SVLAN_CfgSet GSW_SVLAN_cfg_t 0
GSW_SVLAN_PortCfgGet GSW_SVLAN_portCfg_t 2 0
GSW_SVLAN_PortCfgSet GSW_SVLAN_portCfg_t 0
GSW_VLAN_Member_Init GSW_VLAN_memberInit_t 0
GSW_VLAN_IdCreate GSW_VLAN_IdCreate_t 0
GSW_VLAN_IdDelete GSW_VLAN_IdDelete_t 0
GSW_VLAN_IdGet GSW_VLAN_IdGet_t 2 0
GSW_VLAN_PortCfgGet GSW_VLAN_portCfg_t 2 0
GSW_VLAN_PortCfgSet GSW_VLAN_portCfg_t 0
GSW_VLAN_PortMemberAdd GSW_VLAN_portMemberAdd_t 0
GSW_VLAN_PortMemberRead GSW_VLAN_portMemberRead_t 2 0
GSW_VLAN_PortMemberRemove GSW_VLAN_portMemberRemove_t 0
GSW_VLAN_ReservedAdd GSW_VLAN_reserved_t 0
GSW_VLAN_ReservedRemove GSW_VLAN_reserved_t 0
GSW_QoS_ClassDSCP_Get GSW_QoS_ClassDSCP_Cfg_t 3
GSW_QoS_ClassDSCP_Set GSW_QoS_ClassDSCP_Cfg_t 0
GSW_QoS_ClassPCP_Get GSW_QoS_ClassPCP_Cfg_t 3
GSW_QoS_ClassPCP_Set GSW_QoS_ClassPCP_Cfg_t 0
GSW_QoS_DSCP_ClassGet GSW_QoS_DSCP_ClassCfg_t 3
GSW_QoS_DSCP_ClassSet GSW_QoS_DSCP_ClassCfg_t 0
GSW_QoS_DSCP_DropPrecedenceCfgGet GSW_QoS_DSCP_DropPrecedenceCfg_t 3
GSW_QoS_DSCP_DropPrecedenceCfgSet GSW_QoS_DSCP_DropPrecedenceCfg_t 0
GSW_QoS_FlowctrlCfgGet GSW_QoS_FlowCtrlCfg_t 3
GSW_QoS_FlowctrlCfgSet GSW_QoS_FlowCtrlCfg_t 0
GSW_QoS_FlowctrlPortCfgGet GSW_QoS_FlowCtrlPortCfg_t 2 0
GSW_QoS_FlowctrlPortCfgSet GSW_QoS_FlowCtrlPortCfg_t 0
GSW_QoS_MeterCfgGet GSW_QoS_meterCfg_t 2 1
GSW_QoS_MeterCfgSet GSW_QoS_meterCfg_t 0
GSW_QoS_MeterPortAssign GSW_QoS_meterPort_t 0
GSW_QoS_MeterPortDeassign GSW_QoS_meterPort_t 2 0 2 3
GSW_QoS_MeterPortGet GSW_QoS_meterPortGet_t 2 0
GSW_QoS_PCP_ClassGet GSW_QoS_PCP_ClassCfg_t 3
GSW_QoS_PCP_ClassSet GSW_QoS_PCP_ClassCfg_t 0
GSW_QoS_PortCfgGet GSW_QoS_portCfg_t 2 0
GSW_QoS_PortCfgSet GSW_QoS_portCfg_t 0
GSW_QoS_PortRemarkingCfgGet GSW_QoS_portRemarkingCfg_t 2 0
GSW_QoS_PortRemarkingCfgSet GSW_QoS_portRemarkingCfg_t 0
GSW_QoS_QueueBufferReserveCfgGet GSW_QoS_QueueBufferReserveCfg_t 2 0
GSW_QoS_QueueBufferReserveCfgSet GSW_QoS_QueueBufferReserveCfg_t 0
GSW_QoS_QueuePortGet GSW_QoS_queuePort_t 2 0 1
GSW_QoS_QueuePortSet GSW_QoS_queuePort_t 0
GSW_QoS_SVLAN_ClassPCP_PortGet GSW_QoS_SVLAN_ClassPCP_PortCfg_t 2 0
GSW_QoS_SVLAN_ClassPCP_PortSet GSW_QoS_SVLAN_ClassPCP_PortCfg_t 0
GSW_QoS_SVLAN_PCP_ClassGet GSW_QoS_SVLAN_PCP_ClassCfg_t 3
GSW_QoS_SVLAN_PCP_ClassSet GSW_QoS_SVLAN_PCP_ClassCfg_t 0
GSW_QoS_SchedulerCfgGet GSW_QoS_schedulerCfg_t 2 0
GSW_QoS_SchedulerCfgSet GSW_QoS_schedulerCfg_t 0
GSW_QoS_ShaperCfgGet GSW_QoS_ShaperCfg_t 2 0
GSW_QoS_ShaperCfgSet GSW_QoS_ShaperCfg_t 0
GSW_QoS_ShaperQueueAssign GSW_QoS_ShaperQueue_t 0
GSW_QoS_ShaperQueueDeassign GSW_QoS_ShaperQueue_t 0
GSW_QoS_ShaperQueueGet GSW_QoS_ShaperQueueGet_t 2 0
GSW_QoS_StormCfgGet GSW_QoS_stormCfg_t 3
GSW_QoS_StormCfgSet GSW_QoS_stormCfg_t 0
GSW_QoS_WredCfgGet GSW_QoS_WRED_Cfg_t 3
GSW_QoS_WredCfgSet GSW_QoS_WRED_Cfg_t 0
GSW_QoS_WredPortCfgGet GSW_QoS_WRED_PortCfg_t 2 0
GSW_QoS_WredPortCfgSet GSW_QoS_WRED_PortCfg_t 0
GSW_QoS_WredQueueCfgGet GSW_QoS_WRED_QueueCfg_t 2 0
GSW_QoS_WredQueueCfgSet GSW_QoS_WRED_QueueCfg_t 0
GSW_MulticastRouterPortAdd GSW_multicastRouter_t 0
GSW_MulticastRouterPortRead GSW_multicastRouterRead_t 2 0
GSW_MulticastRouterPortRemove GSW_multicastRouter_t 0
GSW_MulticastSnoopCfgGet GSW_multicastSnoopCfg_t 3
GSW_MulticastSnoopCfgSet GSW_multicastSnoopCfg_t 0
GSW_MulticastTableEntryAdd GSW_multicastTable_t 0
GSW_MulticastTableEntryRead GSW_multicastTableRead_t 2 0
GSW_MulticastTableEntryRemove GSW_multicastTable_t 0
GSW_CPU_PortCfgGet GSW_CPU_PortCfg_t 2 0
GSW_CPU_PortCfgSet GSW_CPU_PortCfg_t 0
GSW_CapGet GSW_cap_t 2 0
GSW_CfgGet GSW_cfg_t 3
GSW_CfgSet GSW_cfg_t 0
GSW_Disable 1
GSW_Enable 1
GSW_HW_Init GSW_HW_Init_t 0
GSW_MDIO_CfgGet GSW_MDIO_cfg_t 3
GSW_MDIO_CfgSet GSW_MDIO_cfg_t 0
GSW_MDIO_DataRead GSW_MDIO_data_t 2 0 1
GSW_MDIO_DataWrite GSW_MDIO_data_t 0
GSW_MonitorPortCfgGet GSW_monitorPortCfg_t 2 0
GSW_MonitorPortCfgSet GSW_monitorPortCfg_t 0
GSW_PortCfgGet GSW_portCfg_t 2 0
GSW_PortCfgSet GSW_portCfg_t 0
GSW_PortLinkCfgGet GSW_portLinkCfg_t 2 0
GSW_PortLinkCfgSet GSW_portLinkCfg_t 0
GSW_PortPHY_AddrGet GSW_portPHY_Addr_t 2 0
GSW_PortPHY_Query GSW_portPHY_Query_t 2 0
GSW_PortRGMII_ClkCfgGet GSW_portRGMII_ClkCfg_t 2 0
GSW_PortRGMII_ClkCfgSet GSW_portRGMII_ClkCfg_t 0
GSW_PortRedirectGet GSW_portRedirectCfg_t 2 0
GSW_PortRedirectSet GSW_portRedirectCfg_t 0
GSW_RMON_Clear GSW_RMON_clear_t 0
GSW_RMON_Port_Get GSW_RMON_Port_cnt_t 2 0
GSW_VersionGet GSW_version_t 2 0
GSW_WoL_CfgGet GSW_WoL_Cfg_t 3
GSW_WoL_CfgSet GSW_WoL_Cfg_t 0
GSW_WoL_PortCfgGet GSW_WoL_PortCfg_t 2 0
GSW_WoL_PortCfgSet GSW_WoL_PortCfg_t 0
GSW_RegisterGet GSW_register_t 2 0
GSW_RegisterSet GSW_register_t 0
GSW_IrqMaskGet GSW_irq_t 2 0
GSW_IrqMaskSet GSW_irq_t 0
GSW_PceRuleDelete GSW_PCE_ruleDelete_t 0
GSW_PceRuleRead GSW_PCE_rule_t 5 
GSW_PceRuleWrite GSW_PCE_rule_t 4
GSW_RMON_ExtendGet GSW_RMON_extendGet_t 2 0
GSW_Reset GSW_reset_t 0
GSW_TimestampPortRead GSW_TIMESTAMP_PortRead_t 2 0
GSW_TimestampTimerGet GSW_TIMESTAMP_Timer_t 3
GSW_TimestampTimerSet GSW_TIMESTAMP_Timer_t 0