struct = {'GSW_register_t': [['u16', 'nRegAddr'], ['u16', 'nData']],
 'GSW_irq_t': [['u32', 'nPortId'], ['GSW_irqSrc_t', 'eIrqSrc']],
 'GSW_PCE_pattern_t': [['int', 'nIndex'],
  ['ltq_bool_t', 'bEnable'],
  ['ltq_bool_t', 'bPortIdEnable'],
  ['u8', 'nPortId'],
  ['ltq_bool_t', 'bDSCP_Enable'],
  ['u8', 'nDSCP'],
  ['ltq_bool_t', 'bPCP_Enable'],
  ['u8', 'nPCP'],
  ['ltq_bool_t', 'bSTAG_PCP_DEI_Enable'],
  ['u8', 'nSTAG_PCP_DEI'],
  ['ltq_bool_t', 'bPktLngEnable'],
  ['u16', 'nPktLng'],
  ['u16', 'nPktLngRange'],
  ['ltq_bool_t', 'bMAC_DstEnable'],
  ['u8', 'nMAC_Dst[6]'],
  ['u16', 'nMAC_DstMask'],
  ['ltq_bool_t', 'bMAC_SrcEnable'],
  ['u8', 'nMAC_Src[6]'],
  ['u16', 'nMAC_SrcMask'],
  ['ltq_bool_t', 'bAppDataMSB_Enable'],
  ['u16', 'nAppDataMSB'],
  ['ltq_bool_t', 'bAppMaskRangeMSB_Select'],
  ['u16', 'nAppMaskRangeMSB'],
  ['ltq_bool_t', 'bAppDataLSB_Enable'],
  ['u16', 'nAppDataLSB'],
  ['ltq_bool_t', 'bAppMaskRangeLSB_Select'],
  ['u16', 'nAppMaskRangeLSB'],
  ['GSW_PCE_IP_t', 'eDstIP_Select'],
  ['GSW_IP_t', 'nDstIP'],
  ['u32', 'nDstIP_Mask'],
  ['GSW_PCE_IP_t', 'eSrcIP_Select'],
  ['GSW_IP_t', 'nSrcIP'],
  ['u32', 'nSrcIP_Mask'],
  ['ltq_bool_t', 'bEtherTypeEnable'],
  ['u16', 'nEtherType'],
  ['u16', 'nEtherTypeMask'],
  ['ltq_bool_t', 'bProtocolEnable'],
  ['u8', 'nProtocol'],
  ['u8', 'nProtocolMask'],
  ['ltq_bool_t', 'bSessionIdEnable'],
  ['u16', 'nSessionId'],
  ['ltq_bool_t', 'bVid'],
  ['u16', 'nVid'],
  ['ltq_bool_t', 'bVidRange_Select'],
  ['u16', 'nVidRange'],
  ['ltq_bool_t', 'bSLAN_Vid'],
  ['u16', 'nSLAN_Vid']],
 'GSW_PCE_action_t': [['GSW_PCE_ActionTrafficClass_t', 'eTrafficClassAction'],
  ['u8', 'nTrafficClassAlternate'],
  ['GSW_PCE_ActionIGMP_Snoop_t', 'eSnoopingTypeAction'],
  ['GSW_PCE_ActionLearning_t', 'eLearningAction'],
  ['GSW_PCE_ActionIrq_t', 'eIrqAction'],
  ['GSW_PCE_ActionCrossState_t', 'eCrossStateAction'],
  ['GSW_PCE_ActionCriticalFrame_t', 'eCritFrameAction'],
  ['GSW_PCE_ActionTimestamp_t', 'eTimestampAction'],
  ['GSW_PCE_ActionPortmap_t', 'ePortMapAction'],
  ['u32', 'nForwardPortMap'],
  ['ltq_bool_t', 'bRemarkAction'],
  ['ltq_bool_t', 'bRemarkPCP'],
  ['ltq_bool_t', 'bRemarkSTAG_PCP'],
  ['ltq_bool_t', 'bRemarkSTAG_DEI'],
  ['ltq_bool_t', 'bRemarkDSCP'],
  ['ltq_bool_t', 'bRemarkClass'],
  ['GSW_PCE_ActionMeter_t', 'eMeterAction'],
  ['u8', 'nMeterId'],
  ['ltq_bool_t', 'bRMON_Action'],
  ['u8', 'nRMON_Id'],
  ['GSW_PCE_ActionVLAN_t', 'eVLAN_Action'],
  ['u16', 'nVLAN_Id'],
  ['u8', 'nFId'],
  ['GSW_PCE_ActionVLAN_t', 'eSVLAN_Action'],
  ['u16', 'nSVLAN_Id'],
  ['GSW_PCE_ActionCrossVLAN_t', 'eVLAN_CrossAction'],
  ['ltq_bool_t', 'bCVLAN_Ignore_Control'],
  ['ltq_bool_t', 'bPortBitMapMuxControl'],
  ['ltq_bool_t', 'bPortTrunkAction'],
  ['ltq_bool_t', 'bPortLinkSelection'],
  ['ltq_bool_t', 'bFlowID_Action'],
  ['u16', 'nFlowID']],
 'GSW_PCE_rule_t': [['GSW_PCE_pattern_t', 'pattern'],
  ['GSW_PCE_action_t', 'action']],
 'GSW_PCE_ruleDelete_t': [['u32', 'nIndex']],
 'GSW_reset_t': [['GSW_resetMode_t', 'eReset']],
 'GSW_RMON_extendGet_t': [['u8', 'nPortId'], ['u32', 'nTrafficFlowCnt[24]']],
 'GSW_TIMESTAMP_Timer_t': [['u32', 'nSec'],
  ['u32', 'nNanoSec'],
  ['u32', 'nFractionalNanoSec']],
 'GSW_TIMESTAMP_PortRead_t': [['u8', 'nPortId'],
  ['u32', 'nIngressSec'],
  ['u32', 'nIngressNanoSec'],
  ['u32', 'nEgressSec'],
  ['u32', 'nEgressNanoSec']],
 'GSW_MAC_tableRead_t': [['ltq_bool_t', 'bInitial'],
  ['ltq_bool_t', 'bLast'],
  ['u32', 'nFId'],
  ['u32', 'nPortId'],
  ['int', 'nAgeTimer'],
  ['u16', 'nSVLAN_Id'],
  ['ltq_bool_t', 'bStaticEntry'],
  ['u8', 'nMAC[6]']],
 'GSW_MAC_tableQuery_t': [['u8', 'nMAC[6]'],
  ['u32', 'nFId'],
  ['ltq_bool_t', 'bFound'],
  ['u32', 'nPortId'],
  ['int', 'nAgeTimer'],
  ['u16', 'nSVLAN_Id'],
  ['ltq_bool_t', 'bStaticEntry']],
 'GSW_MAC_tableAdd_t': [['u32', 'nFId'],
  ['u32', 'nPortId'],
  ['int', 'nAgeTimer'],
  ['u16', 'nSVLAN_Id'],
  ['ltq_bool_t', 'bStaticEntry'],
  ['u8', 'nTrafficClass'],
  ['u8', 'nMAC[6]']],
 'GSW_MAC_tableRemove_t': [['u32', 'nFId'], ['u8', 'nMAC[6]']],
 'GSW_STP_portCfg_t': [['u8', 'nPortId'],
  ['u32', 'nFId'],
  ['GSW_STP_PortState_t', 'ePortState']],
 'GSW_STP_BPDU_Rule_t': [['GSW_portForward_t', 'eForwardPort'],
  ['u8', 'nForwardPortId']],
 'GSW_8021X_EAPOL_Rule_t': [['GSW_portForward_t', 'eForwardPort'],
  ['u8', 'nForwardPortId']],
 'GSW_8021X_portCfg_t': [['u32', 'nPortId'],
  ['GSW_8021X_portState_t', 'eState']],
 'GSW_trunkingCfg_t': [['ltq_bool_t', 'bIP_Src'],
  ['ltq_bool_t', 'bIP_Dst'],
  ['ltq_bool_t', 'bMAC_Src'],
  ['ltq_bool_t', 'bMAC_Dst']],
 'GSW_trunkingPortCfg_t': [['ltq_bool_t', 'bAggregateEnable'],
  ['u32', 'nPortId'],
  ['u32', 'nAggrPortId']],
 'GSW_VLAN_IdCreate_t': [['u16', 'nVId'], ['u32', 'nFId']],
 'GSW_VLAN_IdGet_t': [['u16', 'nVId'], ['u32', 'nFId']],
 'GSW_VLAN_memberInit_t': [['u32', 'nPortMemberMap'],
  ['u32', 'nEgressTagMap']],
 'GSW_VLAN_IdDelete_t': [['u16', 'nVId']],
 'GSW_VLAN_portMemberAdd_t': [['u16', 'nVId'],
  ['u32', 'nPortId'],
  ['ltq_bool_t', 'bVLAN_TagEgress']],
 'GSW_VLAN_portMemberRemove_t': [['u16', 'nVId'], ['u32', 'nPortId']],
 'GSW_VLAN_portMemberRead_t': [['ltq_bool_t', 'bInitial'],
  ['ltq_bool_t', 'bLast'],
  ['u16', 'nVId'],
  ['u32', 'nPortId'],
  ['u32', 'nTagId']],
 'GSW_VLAN_portCfg_t': [['u8', 'nPortId'],
  ['u16', 'nPortVId'],
  ['ltq_bool_t', 'bVLAN_UnknownDrop'],
  ['ltq_bool_t', 'bVLAN_ReAssign'],
  ['GSW_VLAN_MemberViolation_t', 'eVLAN_MemberViolation'],
  ['GSW_VLAN_Admit_t', 'eAdmitMode'],
  ['ltq_bool_t', 'bTVM']],
 'GSW_VLAN_reserved_t': [['u16', 'nVId']],
 'GSW_SVLAN_cfg_t': [['u16', 'nEthertype']],
 'GSW_SVLAN_portCfg_t': [['u8', 'nPortId'],
  ['ltq_bool_t', 'bSVLAN_TagSupport'],
  ['ltq_bool_t', 'bSVLAN_MACbasedTag'],
  ['u16', 'nPortVId'],
  ['ltq_bool_t', 'bVLAN_ReAssign'],
  ['GSW_VLAN_MemberViolation_t', 'eVLAN_MemberViolation'],
  ['GSW_VLAN_Admit_t', 'eAdmitMode']],
 'GSW_QoS_DSCP_ClassCfg_t': [['u32', 'nDSCP'], ['u8', 'nTrafficClass[64]']],
 'GSW_QoS_PCP_ClassCfg_t': [['u8', 'nPCP'], ['u8', 'nTrafficClass[8]']],
 'GSW_QoS_portRemarkingCfg_t': [['u8', 'nPortId'],
  ['GSW_Qos_ingressRemarking_t', 'eDSCP_IngressRemarkingEnable'],
  ['ltq_bool_t', 'bDSCP_EgressRemarkingEnable'],
  ['ltq_bool_t', 'bPCP_IngressRemarkingEnable'],
  ['ltq_bool_t', 'bPCP_EgressRemarkingEnable'],
  ['ltq_bool_t', 'bSTAG_PCP_IngressRemarkingEnable'],
  ['ltq_bool_t', 'bSTAG_DEI_IngressRemarkingEnable'],
  ['ltq_bool_t', 'bSTAG_PCP_DEI_EgressRemarkingEnable']],
 'GSW_QoS_ClassDSCP_Cfg_t': [['u8', 'nTrafficClass'], ['u8', 'nDSCP[16]']],
 'GSW_QoS_ClassPCP_Cfg_t': [['u8', 'nTrafficClass'], ['u8', 'nPCP[16]']],
 'GSW_QoS_DSCP_DropPrecedenceCfg_t': [['u8', 'nDSCP'],
  ['GSW_QoS_DropPrecedence_t', 'nDSCP_DropPrecedence[64]']],
 'GSW_QoS_portCfg_t': [['u8', 'nPortId'],
  ['GSW_QoS_ClassSelect_t', 'eClassMode'],
  ['u8', 'nTrafficClass']],
 'GSW_QoS_ShaperCfg_t': [['u32', 'nRateShaperId'],
  ['ltq_bool_t', 'bEnable'],
  ['ltq_bool_t', 'bAVB'],
  ['u32', 'nCbs'],
  ['u32', 'nRate']],
 'GSW_QoS_ShaperQueue_t': [['u8', 'nRateShaperId'], ['u8', 'nQueueId']],
 'GSW_QoS_ShaperQueueGet_t': [['u8', 'nQueueId'],
  ['ltq_bool_t', 'bAssigned'],
  ['u8', 'nRateShaperId']],
 'GSW_QoS_WRED_Cfg_t': [['GSW_QoS_WRED_Profile_t', 'eProfile'],
  ['GSW_QoS_WRED_ThreshMode_t', 'eThreshMode'],
  ['u32', 'nRed_Min'],
  ['u32', 'nRed_Max'],
  ['u32', 'nYellow_Min'],
  ['u32', 'nYellow_Max'],
  ['u32', 'nGreen_Min'],
  ['u32', 'nGreen_Max']],
 'GSW_QoS_WRED_QueueCfg_t': [['u32', 'nQueueId'],
  ['u32', 'nRed_Min'],
  ['u32', 'nRed_Max'],
  ['u32', 'nYellow_Min'],
  ['u32', 'nYellow_Max'],
  ['u32', 'nGreen_Min'],
  ['u32', 'nGreen_Max']],
 'GSW_QoS_WRED_PortCfg_t': [['u32', 'nPortId'],
  ['u32', 'nRed_Min'],
  ['u32', 'nRed_Max'],
  ['u32', 'nYellow_Min'],
  ['u32', 'nYellow_Max'],
  ['u32', 'nGreen_Min'],
  ['u32', 'nGreen_Max']],
 'GSW_QoS_FlowCtrlCfg_t': [['u32', 'nFlowCtrlNonConform_Min'],
  ['u32', 'nFlowCtrlNonConform_Max'],
  ['u32', 'nFlowCtrlConform_Min'],
  ['u32', 'nFlowCtrlConform_Max']],
 'GSW_QoS_FlowCtrlPortCfg_t': [['u32', 'nPortId'],
  ['u32', 'nFlowCtrl_Min'],
  ['u32', 'nFlowCtrl_Max']],
 'GSW_QoS_meterCfg_t': [['ltq_bool_t', 'bEnable'],
  ['u32', 'nMeterId'],
  ['u32', 'nCbs'],
  ['u32', 'nEbs'],
  ['u32', 'nRate']],
 'GSW_QoS_meterPort_t': [['u32', 'nMeterId'],
  ['GSW_direction_t', 'eDir'],
  ['u32', 'nPortIngressId'],
  ['u32', 'nPortEgressId']],
 'GSW_QoS_meterPortGet_t': [['ltq_bool_t', 'bInitial'],
  ['ltq_bool_t', 'bLast'],
  ['GSW_direction_t', 'eDir'],
  ['u8', 'nMeterId'],
  ['u8', 'nPortIngressId'],
  ['u8', 'nPortEgressId']],
 'GSW_QoS_stormCfg_t': [['int', 'nMeterId'],
  ['ltq_bool_t', 'bBroadcast'],
  ['ltq_bool_t', 'bMulticast'],
  ['ltq_bool_t', 'bUnknownUnicast']],
 'GSW_QoS_schedulerCfg_t': [['u8', 'nQueueId'],
  ['GSW_QoS_Scheduler_t', 'eType'],
  ['u32', 'nWeight']],
 'GSW_QoS_queuePort_t': [['u8', 'nPortId'],
  ['u8', 'nTrafficClassId'],
  ['u8', 'nQueueId']],
 'GSW_QoS_QueueBufferReserveCfg_t': [['u8', 'nQueueId'],
  ['u32', 'nBufferReserved']],
 'GSW_QoS_SVLAN_ClassPCP_PortCfg_t': [['u8', 'nPortId'],
  ['u8', 'nTrafficClass'],
  ['u8', 'nCPCP[16]'],
  ['u8', 'nSPCP[16]'],
  ['u8', 'nDSCP[16]']],
 'GSW_QoS_SVLAN_PCP_ClassCfg_t': [['u8', 'nTrafficClass[16]'],
  ['u8', 'nTrafficColor[16]'],
  ['u8', 'nPCP_Remark_Enable[16]'],
  ['u8', 'nDEI_Remark_Enable[16]']],
 'GSW_multicastSnoopCfg_t': [['GSW_multicastSnoopMode_t', 'eIGMP_Mode'],
  ['ltq_bool_t', 'bIGMPv3'],
  ['ltq_bool_t', 'bCrossVLAN'],
  ['GSW_portForward_t', 'eForwardPort'],
  ['u8', 'nForwardPortId'],
  ['u8', 'nClassOfService'],
  ['u8', 'nRobust'],
  ['u8', 'nQueryInterval'],
  ['GSW_multicastReportSuppression_t', 'eSuppressionAggregation'],
  ['ltq_bool_t', 'bFastLeave'],
  ['ltq_bool_t', 'bLearningRouter'],
  ['ltq_bool_t', 'bMulticastUnknownDrop']],
 'GSW_multicastRouter_t': [['u8', 'nPortId']],
 'GSW_multicastRouterRead_t': [['ltq_bool_t', 'bInitial'],
  ['ltq_bool_t', 'bLast'],
  ['u8', 'nPortId']],
 'GSW_multicastTable_t': [['u32', 'nPortId'],
  ['GSW_IP_Select_t', 'eIPVersion'],
  ['GSW_IP_t', 'uIP_Gda'],
  ['GSW_IP_t', 'uIP_Gsa'],
  ['GSW_IGMP_MemberMode_t', 'eModeMember']],
 'GSW_multicastTableRead_t': [['ltq_bool_t', 'bInitial'],
  ['ltq_bool_t', 'bLast'],
  ['u8', 'nPortId'],
  ['GSW_IP_Select_t', 'eIPVersion'],
  ['GSW_IP_t', 'uIP_Gda'],
  ['GSW_IP_t', 'uIP_Gsa'],
  ['GSW_IGMP_MemberMode_t', 'eModeMember']],
 'GSW_version_t': [['u16', 'nId'],
  ['char', 'cName[64]'],
  ['char', 'cVersion[64]']],
 'GSW_HW_Init_t': [['GSW_HW_InitMode_t', 'eInitMode']],
 'GSW_cap_t': [['GSW_capType_t', 'nCapType'],
  ['char', 'cDesc[128]'],
  ['u32', 'nCap']],
 'GSW_cfg_t': [['GSW_ageTimer_t', 'eMAC_TableAgeTimer'],
  ['ltq_bool_t', 'bVLAN_Aware'],
  ['u16', 'nMaxPacketLen'],
  ['ltq_bool_t', 'bLearningLimitAction'],
  ['ltq_bool_t', 'bMAC_SpoofingAction'],
  ['ltq_bool_t', 'bPauseMAC_ModeSrc'],
  ['u8', 'nPauseMAC_Src[6]']],
 'GSW_portCfg_t': [['u8', 'nPortId'],
  ['GSW_portEnable_t', 'eEnable'],
  ['ltq_bool_t', 'bUnicastUnknownDrop'],
  ['ltq_bool_t', 'bMulticastUnknownDrop'],
  ['ltq_bool_t', 'bReservedPacketDrop'],
  ['ltq_bool_t', 'bBroadcastDrop'],
  ['ltq_bool_t', 'bAging'],
  ['ltq_bool_t', 'bLearning'],
  ['ltq_bool_t', 'bLearningMAC_PortLock'],
  ['u16', 'nLearningLimit'],
  ['ltq_bool_t', 'bMAC_SpoofingDetection'],
  ['GSW_portFlow_t', 'eFlowCtrl'],
  ['GSW_portMonitor_t', 'ePortMonitor']],
 'GSW_CPU_PortCfg_t': [['u8', 'nPortId'],
  ['ltq_bool_t', 'bCPU_PortValid'],
  ['ltq_bool_t', 'bSpecialTagIngress'],
  ['ltq_bool_t', 'bSpecialTagEgress'],
  ['ltq_bool_t', 'bFcsCheck'],
  ['ltq_bool_t', 'bFcsGenerate'],
  ['GSW_CPU_SpecialTagEthType_t', 'bSpecialTagEthType']],
 'GSW_CPU_Header_t': [['u8', 'nMAC_Src[6]'],
  ['u8', 'nMAC_Dst[6]'],
  ['u16', 'nEthertype'],
  ['u8', 'nVLAN_Prio'],
  ['u8', 'nVLAN_CFI'],
  ['u16', 'nVLAN_ID']],
 'GSW_CPU_PortExtendCfg_t': [['GSW_CPU_HeaderMode_t', 'eHeaderAdd'],
  ['ltq_bool_t', 'bHeaderRemove'],
  ['GSW_CPU_Header_t', 'sHeader'],
  ['GSW_CPU_Pause_t', 'ePauseCtrl'],
  ['ltq_bool_t', 'bFcsRemove'],
  ['u32', 'nWAN_Ports']],
 'GSW_portLinkCfg_t': [['u8', 'nPortId'],
  ['ltq_bool_t', 'bDuplexForce'],
  ['GSW_portDuplex_t', 'eDuplex'],
  ['ltq_bool_t', 'bSpeedForce'],
  ['GSW_portSpeed_t', 'eSpeed'],
  ['ltq_bool_t', 'bLinkForce'],
  ['GSW_portLink_t', 'eLink'],
  ['GSW_MII_Mode_t', 'eMII_Mode'],
  ['GSW_MII_Type_t', 'eMII_Type'],
  ['GSW_clkMode_t', 'eClkMode'],
  ['ltq_bool_t', 'bLPI']],
 'GSW_portRGMII_ClkCfg_t': [['u8', 'nPortId'],
  ['u8', 'nDelayRx'],
  ['u8', 'nDelayTx']],
 'GSW_portPHY_Query_t': [['u8', 'nPortId'], ['ltq_bool_t', 'bPHY_Present']],
 'GSW_portPHY_Addr_t': [['u8', 'nPortId'], ['u8', 'nAddressDev']],
 'GSW_portRedirectCfg_t': [['u8', 'nPortId'],
  ['ltq_bool_t', 'bRedirectEgress'],
  ['ltq_bool_t', 'bRedirectIngress']],
 'GSW_monitorPortCfg_t': [['u8', 'nPortId'], ['ltq_bool_t', 'bMonitorPort']],
 'GSW_MDIO_cfg_t': [['u32', 'nMDIO_Speed'], ['ltq_bool_t', 'bMDIO_Enable']],
 'GSW_MDIO_data_t': [['u8', 'nAddressDev'],
  ['u8', 'nAddressReg'],
  ['u16', 'nData']],
 'GSW_MMD_data_t': [['u8', 'nAddressDev'],
  ['u32', 'nAddressReg'],
  ['u16', 'nData']],
 'GSW_WoL_Cfg_t': [['u8', 'nWolMAC[6]'],
  ['u8', 'nWolPassword[6]'],
  ['ltq_bool_t', 'bWolPasswordEnable']],
 'GSW_WoL_PortCfg_t': [['u8', 'nPortId'], ['ltq_bool_t', 'bWakeOnLAN_Enable']],
 'GSW_RMON_clear_t': [['GSW_RMON_type_t', 'eRmonType'], ['u8', 'nRmonId']],
 'GSW_RMON_Port_cnt_t': [['u8', 'nPortId'],
  ['u32', 'nRxGoodPkts'],
  ['u32', 'nRxUnicastPkts'],
  ['u32', 'nRxBroadcastPkts'],
  ['u32', 'nRxMulticastPkts'],
  ['u32', 'nRxFCSErrorPkts'],
  ['u32', 'nRxUnderSizeGoodPkts'],
  ['u32', 'nRxOversizeGoodPkts'],
  ['u32', 'nRxUnderSizeErrorPkts'],
  ['u32', 'nRxGoodPausePkts'],
  ['u32', 'nRxOversizeErrorPkts'],
  ['u32', 'nRxAlignErrorPkts'],
  ['u32', 'nRxFilteredPkts'],
  ['u32', 'nRx64BytePkts'],
  ['u32', 'nRx127BytePkts'],
  ['u32', 'nRx255BytePkts'],
  ['u32', 'nRx511BytePkts'],
  ['u32', 'nRx1023BytePkts'],
  ['u32', 'nRxMaxBytePkts'],
  ['u32', 'nTxGoodPkts'],
  ['u32', 'nTxUnicastPkts'],
  ['u32', 'nTxBroadcastPkts'],
  ['u32', 'nTxMulticastPkts'],
  ['u32', 'nTxSingleCollCount'],
  ['u32', 'nTxMultCollCount'],
  ['u32', 'nTxLateCollCount'],
  ['u32', 'nTxExcessCollCount'],
  ['u32', 'nTxCollCount'],
  ['u32', 'nTxPauseCount'],
  ['u32', 'nTx64BytePkts'],
  ['u32', 'nTx127BytePkts'],
  ['u32', 'nTx255BytePkts'],
  ['u32', 'nTx511BytePkts'],
  ['u32', 'nTx1023BytePkts'],
  ['u32', 'nTxMaxBytePkts'],
  ['u32', 'nTxDroppedPkts'],
  ['u32', 'nTxAcmDroppedPkts'],
  ['u32', 'nRxDroppedPkts'],
  ['u64', 'nRxGoodBytes'],
  ['u64', 'nRxBadBytes'],
  ['u64', 'nTxGoodBytes']],
 'GSW_RMON_mode_t': [['GSW_RMON_type_t', 'eRmonType'],
  ['GSW_RMON_CountMode_t', 'eCountMode']]}

enum = {'GSW_irqSrc_t': {'0': 'GSW_IRQ_WOL',
  '1': 'GSW_IRQ_LIMIT_ALERT',
  '2': 'GSW_IRQ_LOCK_ALERT'},
 'GSW_PCE_IP_t': {'0': 'GSW_PCE_IP_DISABLED',
  '1': 'GSW_PCE_IP_V4',
  '2': 'GSW_PCE_IP_V6'},
 'GSW_PCE_ActionIGMP_Snoop_t': {'0': 'GSW_PCE_ACTION_IGMP_SNOOP_DISABLE',
  '1': 'GSW_PCE_ACTION_IGMP_SNOOP_REGULAR',
  '2': 'GSW_PCE_ACTION_IGMP_SNOOP_REPORT',
  '3': 'GSW_PCE_ACTION_IGMP_SNOOP_LEAVE',
  '4': 'GSW_PCE_ACTION_IGMP_SNOOP_AD',
  '5': 'GSW_PCE_ACTION_IGMP_SNOOP_QUERY',
  '6': 'GSW_PCE_ACTION_IGMP_SNOOP_QUERY_GROUP',
  '7': 'GSW_PCE_ACTION_IGMP_SNOOP_QUERY_NO_ROUTER'},
 'GSW_PCE_ActionLearning_t': {'0': 'GSW_PCE_ACTION_LEARNING_DISABLE',
  '1': 'GSW_PCE_ACTION_LEARNING_REGULAR',
  '2': 'GSW_PCE_ACTION_LEARNING_FORCE_NOT',
  '3': 'GSW_PCE_ACTION_LEARNING_FORCE'},
 'GSW_PCE_ActionMeter_t': {'0': 'GSW_PCE_ACTION_METER_DISABLE',
  '1': 'GSW_PCE_ACTION_METER_REGULAR',
  '2': 'GSW_PCE_ACTION_METER_1',
  '3': 'GSW_PCE_ACTION_METER_1_2'},
 'GSW_PCE_ActionTrafficClass_t': {'0': 'GSW_PCE_ACTION_TRAFFIC_CLASS_DISABLE',
  '1': 'GSW_PCE_ACTION_TRAFFIC_CLASS_REGULAR',
  '2': 'GSW_PCE_ACTION_TRAFFIC_CLASS_ALTERNATIVE'},
 'GSW_PCE_ActionIrq_t': {'0': 'GSW_PCE_ACTION_IRQ_DISABLE',
  '1': 'GSW_PCE_ACTION_IRQ_REGULAR',
  '2': 'GSW_PCE_ACTION_IRQ_EVENT'},
 'GSW_PCE_ActionCrossState_t': {'0': 'GSW_PCE_ACTION_CROSS_STATE_DISABLE',
  '1': 'GSW_PCE_ACTION_CROSS_STATE_REGULAR',
  '2': 'GSW_PCE_ACTION_CROSS_STATE_CROSS'},
 'GSW_PCE_ActionCriticalFrame_t': {'0': 'GSW_PCE_ACTION_CRITICAL_FRAME_DISABLE',
  '1': 'GSW_PCE_ACTION_CRITICAL_FRAME_REGULAR',
  '2': 'GSW_PCE_ACTION_CRITICAL_FRAME_CRITICAL'},
 'GSW_PCE_ActionTimestamp_t': {'0': 'GSW_PCE_ACTION_TIMESTAMP_DISABLE',
  '1': 'GSW_PCE_ACTION_TIMESTAMP_REGULAR',
  '2': 'GSW_PCE_ACTION_TIMESTAMP_STORED'},
 'GSW_PCE_ActionPortmap_t': {'0': 'GSW_PCE_ACTION_PORTMAP_DISABLE',
  '1': 'GSW_PCE_ACTION_PORTMAP_REGULAR',
  '2': 'GSW_PCE_ACTION_PORTMAP_DISCARD',
  '3': 'GSW_PCE_ACTION_PORTMAP_CPU',
  '4': 'GSW_PCE_ACTION_PORTMAP_ALTERNATIVE',
  '5': 'GSW_PCE_ACTION_PORTMAP_MULTICAST_ROUTER',
  '6': 'GSW_PCE_ACTION_PORTMAP_MULTICAST_HW_TABLE',
  '7': 'GSW_PCE_ACTION_PORTMAP_ALTERNATIVE_VLAN',
  '8': 'GSW_PCE_ACTION_PORTMAP_ALTERNATIVE_STAG_VLAN'},
 'GSW_PCE_ActionVLAN_t': {'0': 'GSW_PCE_ACTION_VLAN_DISABLE',
  '1': 'GSW_PCE_ACTION_VLAN_REGULAR',
  '2': 'GSW_PCE_ACTION_VLAN_ALTERNATIVE'},
 'GSW_PCE_ActionCrossVLAN_t': {'0': 'GSW_PCE_ACTION_CROSS_VLAN_DISABLE',
  '1': 'GSW_PCE_ACTION_CROSS_VLAN_REGULAR',
  '2': 'GSW_PCE_ACTION_CROSS_VLAN_CROSS'},
 'GSW_resetMode_t': {'0': 'GSW_RESET_SWITCH', '1': 'GSW_RESET_MDIO'},
 'GSW_portForward_t': {'0': 'GSW_PORT_FORWARD_DEFAULT',
  '1': 'GSW_PORT_FORWARD_DISCARD',
  '2': 'GSW_PORT_FORWARD_CPU',
  '3': 'GSW_PORT_FORWARD_PORT'},
 'GSW_STP_PortState_t': {'0': 'GSW_STP_PORT_STATE_FORWARD',
  '1': 'GSW_STP_PORT_STATE_DISABLE',
  '2': 'GSW_STP_PORT_STATE_LEARNING',
  '3': 'GSW_STP_PORT_STATE_BLOCKING'},
 'GSW_8021X_portState_t': {'0': 'GSW_8021X_PORT_STATE_AUTHORIZED',
  '1': 'GSW_8021X_PORT_STATE_UNAUTHORIZED',
  '2': 'GSW_8021X_PORT_STATE_RX_AUTHORIZED',
  '3': 'GSW_8021X_PORT_STATE_TX_AUTHORIZED'},
 'GSW_VLAN_Admit_t': {'0': 'GSW_VLAN_ADMIT_ALL',
  '1': 'GSW_VLAN_ADMIT_UNTAGGED',
  '2': 'GSW_VLAN_ADMIT_TAGGED'},
 'GSW_VLAN_MemberViolation_t': {'0': 'GSW_VLAN_MEMBER_VIOLATION_NO',
  '1': 'GSW_VLAN_MEMBER_VIOLATION_INGRESS',
  '2': 'GSW_VLAN_MEMBER_VIOLATION_EGRESS',
  '3': 'GSW_VLAN_MEMBER_VIOLATION_BOTH'},
 'GSW_Qos_ingressRemarking_t': {'0': 'GSW_DSCP_REMARK_DISABLE',
  '1': 'GSW_DSCP_REMARK_TC6',
  '2': 'GSW_DSCP_REMARK_TC3',
  '3': 'GSW_DSCP_REMARK_DP3',
  '4': 'GSW_DSCP_REMARK_DP3_TC3'},
 'GSW_QoS_DropPrecedence_t': {'0': 'GSW_DROP_PRECEDENCE_CRITICAL',
  '1': 'GSW_DROP_PRECEDENCE_GREEN',
  '2': 'GSW_DROP_PRECEDENCE_YELLOW',
  '3': 'GSW_DROP_PRECEDENCE_RED'},
 'GSW_QoS_ClassSelect_t': {'0': 'GSW_QOS_CLASS_SELECT_NO',
  '1': 'GSW_QOS_CLASS_SELECT_DSCP',
  '2': 'GSW_QOS_CLASS_SELECT_PCP',
  '3': 'GSW_QOS_CLASS_SELECT_DSCP_PCP',
  '4': 'GSW_QOS_CLASS_SELECT_PCP_DSCP',
  '5': 'GSW_QOS_CLASS_SELECT_SPCP',
  '6': 'GSW_QOS_CLASS_SELECT_SPCP_DSCP',
  '7': 'GSW_QOS_CLASS_SELECT_DSCP_SPCP',
  '8': 'GSW_QOS_CLASS_SELECT_SPCP_PCP',
  '9': 'GSW_QOS_CLASS_SELECT_SPCP_PCP_DSCP',
  '10': 'GSW_QOS_CLASS_SELECT_DSCP_SPCP_PCP'},
 'GSW_QoS_WRED_ThreshMode_t': {'0': 'GSW_QOS_WRED_Local_Thresh',
  '1': 'GSW_QOS_WRED_Global_Thresh'},
 'GSW_QoS_WRED_Profile_t': {'0': 'GSW_QOS_WRED_PROFILE_P0',
  '1': 'GSW_QOS_WRED_PROFILE_P1',
  '2': 'GSW_QOS_WRED_PROFILE_P2',
  '3': 'GSW_QOS_WRED_PROFILE_P3'},
 'GSW_direction_t': {'0': 'GSW_DIRECTION_NONE',
  '1': 'GSW_DIRECTION_INGRESS',
  '2': 'GSW_DIRECTION_EGRESS',
  '3': 'GSW_DIRECTION_BOTH'},
 'GSW_QoS_Scheduler_t': {'0': 'GSW_QOS_SCHEDULER_STRICT',
  '1': 'GSW_QOS_SCHEDULER_WFQ'},
 'GSW_multicastSnoopMode_t': {'0': 'GSW_MULTICAST_SNOOP_MODE_DISABLED',
  '1': 'GSW_MULTICAST_SNOOP_MODE_AUTOLEARNING',
  '2': 'GSW_MULTICAST_SNOOP_MODE_FORWARD'},
 'GSW_multicastReportSuppression_t': {'0': 'GSW_MULTICAST_REPORT_JOIN',
  '1': 'GSW_MULTICAST_REPORT',
  '2': 'GSW_MULTICAST_TRANSPARENT'},
 'GSW_IGMP_MemberMode_t': {'0': 'GSW_IGMP_MEMBER_INCLUDE',
  '1': 'GSW_IGMP_MEMBER_EXCLUDE',
  '2': 'GSW_IGMP_MEMBER_DONT_CARE'},
 'GSW_HW_InitMode_t': {'0': 'GSW_HW_INIT_WR',
  '1': 'GSW_HW_INIT_RO',
  '2': 'GSW_HW_INIT_NO'},
 'GSW_ageTimer_t': {'1': 'GSW_AGETIMER_1_SEC',
  '2': 'GSW_AGETIMER_10_SEC',
  '3': 'GSW_AGETIMER_300_SEC',
  '4': 'GSW_AGETIMER_1_HOUR',
  '5': 'GSW_AGETIMER_1_DAY'},
 'GSW_portSpeed_t': {'10': 'GSW_PORT_SPEED_10',
  '100': 'GSW_PORT_SPEED_100',
  '200': 'GSW_PORT_SPEED_200',
  '1000': 'GSW_PORT_SPEED_1000',
  '2500': 'GSW_PORT_SPEED_2500'},
 'GSW_portDuplex_t': {'0': 'GSW_DUPLEX_FULL', '1': 'GSW_DUPLEX_HALF'},
 'GSW_portLink_t': {'0': 'GSW_PORT_LINK_UP', '1': 'GSW_PORT_LINK_DOWN'},
 'GSW_capType_t': {'0': 'GSW_CAP_TYPE_PORT',
  '1': 'GSW_CAP_TYPE_VIRTUAL_PORT',
  '2': 'GSW_CAP_TYPE_BUFFER_SIZE',
  '3': 'GSW_CAP_TYPE_SEGMENT_SIZE',
  '4': 'GSW_CAP_TYPE_PRIORITY_QUEUE',
  '5': 'GSW_CAP_TYPE_METER',
  '6': 'GSW_CAP_TYPE_RATE_SHAPER',
  '7': 'GSW_CAP_TYPE_VLAN_GROUP',
  '8': 'GSW_CAP_TYPE_FID',
  '9': 'GSW_CAP_TYPE_MAC_TABLE_SIZE',
  '10': 'GSW_CAP_TYPE_MULTICAST_TABLE_SIZE',
  '11': 'GSW_CAP_TYPE_PPPOE_SESSION',
  '12': 'GSW_CAP_TYPE_SVLAN_GROUP',
  '13': 'GSW_CAP_TYPE_LAST'},
 'GSW_portEnable_t': {'0': 'GSW_PORT_DISABLE',
  '1': 'GSW_PORT_ENABLE_RXTX',
  '2': 'GSW_PORT_ENABLE_RX',
  '3': 'GSW_PORT_ENABLE_TX'},
 'GSW_portMonitor_t': {'0': 'GSW_PORT_MONITOR_NONE',
  '1': 'GSW_PORT_MONITOR_RX',
  '2': 'GSW_PORT_MONITOR_TX',
  '3': 'GSW_PORT_MONITOR_RXTX',
  '4': 'GSW_PORT_MONITOR_VLAN_UNKNOWN',
  '16': 'GSW_PORT_MONITOR_VLAN_MEMBERSHIP',
  '32': 'GSW_PORT_MONITOR_PORT_STATE',
  '64': 'GSW_PORT_MONITOR_LEARNING_LIMIT',
  '128': 'GSW_PORT_MONITOR_PORT_LOCK'},
 'GSW_portFlow_t': {'0': 'GSW_FLOW_AUTO',
  '1': 'GSW_FLOW_RX',
  '2': 'GSW_FLOW_TX',
  '3': 'GSW_FLOW_RXTX',
  '4': 'GSW_FLOW_OFF'},
 'GSW_CPU_SpecialTagEthType_t': {'0': 'GSW_CPU_ETHTYPE_PREDEFINED',
  '1': 'GSW_CPU_ETHTYPE_FLOWID'},
 'GSW_CPU_HeaderMode_t': {'0': 'GSW_CPU_HEADER_NO',
  '1': 'GSW_CPU_HEADER_MAC',
  '2': 'GSW_CPU_HEADER_VLAN'},
 'GSW_CPU_Pause_t': {'0': 'GSW_CPU_PAUSE_FORWARD',
  '1': 'GSW_CPU_PAUSE_DISPATCH'},
 'GSW_MII_Mode_t': {'0': 'GSW_PORT_HW_MII',
  '1': 'GSW_PORT_HW_RMII',
  '2': 'GSW_PORT_HW_GMII',
  '3': 'GSW_PORT_HW_RGMII'},
 'GSW_MII_Type_t': {'0': 'GSW_PORT_MAC', '1': 'GSW_PORT_PHY'},
 'GSW_clkMode_t': {'0': 'GSW_PORT_CLK_NA',
  '1': 'GSW_PORT_CLK_MASTER',
  '2': 'GSW_PORT_CLK_SLAVE'},
 'GSW_return_t': {'0': 'GSW_statusOk',
  '-1': 'GSW_statusErr',
  '-2': 'GSW_statusParam',
  '-3': 'GSW_statusVLAN_Space',
  '-4': 'GSW_statusVLAN_ID',
  '-5': 'GSW_statusInvalIoctl',
  '-6': 'GSW_statusNoSupport',
  '-7': 'GSW_statusTimeout',
  '-8': 'GSW_statusValueRange',
  '-9': 'GSW_statusPortInvalid',
  '-10': 'GSW_statusIRQ_Invalid',
  '-11': 'GSW_statusMAC_TableFull',
  '-12': 'GSW_statusLock_Failed',
  '-13': 'GSW_statusMemErr',
  '-14': 'GSW_statusBusErr',
  '-15': 'GSW_statusTblFull'},
 'GSW_RMON_type_t': {'0': 'GSW_RMON_ALL_TYPE',
  '1': 'GSW_RMON_PMAC_TYPE',
  '2': 'GSW_RMON_PORT_TYPE',
  '3': 'GSW_RMON_METER_TYPE',
  '4': 'GSW_RMON_IF_TYPE',
  '5': 'GSW_RMON_ROUTE_TYPE',
  '6': 'GSW_RMON_REDIRECT_TYPE'},
 'GSW_RMON_CountMode_t': {'0': 'GSW_RMON_COUNT_PKTS',
  '1': 'GSW_RMON_COUNT_BYTES',
  '2': 'GSW_RMON_DROP_COUNT'}}
  